openapi: 3.0.1
info:
  version: 1.0.0
  title: Serviços Auxiliares
  description: Consulte endereços, liste cidades e pesquise por instituições financeiras. 
servers:
  - url: 'https://api-mtls.sandbox.bankly.com.br'
paths:
  /addresses/{zipCode}:
    get:
      tags:
        - Endereços
      summary: Consulta de endereço por CEP
      description: |
        <div class="bkly-ref-description">
          <p>Realize consultas de endereços através do código postal.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: zipcode.read</span>
        </div>
      
      operationId: GetAddress
      parameters:
        - name: zipCode
          in: path
          description: O CEP correspondente ao endereço
          required: true
          schema:
            type: string
            description: O CEP correspondente ao endereço
            nullable: true
            example: '05402100'
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
              example:
                zipCode: '05402100'
                addressLine: Avenida Rebouças
                neighborhood: Pinheiros
                city: São Paulo
                state: SP
                country: BR
        '400':
          description: Há algum problema com a sua requisição.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Recurso não encontrado.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ocorreu algum erro inexperado no nosso servidor.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Bearer: []
  
  /banklist:
    get:
      tags:
        - Instituições Financeiras
      summary: Listagem de instituições financeiras
      description: |
        <div class="bkly-ref-description">
          <p>Obtenha uma lista de instituições financeiras e suas informações, como o ISPB, os produtos ofertados, o tipo de banco (se é folha, destino ou ambos), dentre outros.</p>
          <span class="bkly-ref-small-beta-tag">beta</span> 
          <span class="bkly-ref-scope-tag">scope: banklist.read</span>
         [block:callout]
        {
          "type": "info",
          "title": "Nota",
          "body": "Caso não seja enviado um valor no campo <code>product</code>, será assumido o valor padrão <b>TED</b>."
        }
        [/block]
        </div>
      operationId: GetBanks
      parameters:
        - name: name
          in: query
          schema:
            type: string
            description: Nome do banco que deseja consultar.
            nullable: true
        - name: product
          in: query
          schema:
            $ref: '#/components/schemas/Product'
        - name: id
          in: query
          schema:
            type: array
            items:
              type: string
            description: "Código do banco. Este campo aceita mais de um valor, o qual resulta em múltiplas consultas. Ex.: id=332&id=223."
            nullable: true
        - name: page
          in: query
          schema:
            type: string
            description: Página que deseja consultar. Caso este campo seja preenchido, o campo <code>pageSize</code> terá como valor padrão 20.
            nullable: true
        - name: pageSize
          in: query
          schema:
            type: string
            description: Quantidade de bancos a serem exibidos por página.
            default: 20
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/authorization"
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
              example:
                - name: Acesso Soluções De Pagamento S.A.
                  ispb: '13140088'
                  code: '332'
                  shortName: Acesso Solucoes Pagamento Sa
                  isSPIDirect: true
                  products:
                    - TED
                    - PIX
                    - accountPortability
                  accountPortabilityTypes:
                    - Payroll
                    - Destination
                - name: Banco Do Brasil S.A.
                  ispb: '00000000'
                  code: '001'
                  shortName: Bco Do Brasil S.A.
                  isSPIDirect: true
                  products:
                    - TED
                    - PIX
                    - accountPortability
                  accountPortabilityTypes:
                    - Payroll
                    - Destination
                - name: Agk Corretora De Cambio S.A.
                  ispb: '00250699'
                  code: '272'
                  shortName: Agk Cc S.A.
                  products:
                    - TED
                    - PIX
                    - accountPortability
                  accountPortabilityTypes:
                    - Destination
        '400':
          description: Há algum problema com a sua requisição.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Recurso não encontrado.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ocorreu algum erro inexperado no nosso servidor.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Bearer: []
  
  /banklist/{id}:
    get:
      tags:
        - Instituições Financeiras
      summary: Consulta de instituições financeiras por ISPB ou código bancário
      description: Consulte informações sobre a instituição financeira através do ISPB ou código bancário.
      operationId: GetBank
      parameters:
        - name: id
          in: path
          description: O Id corresponde ao ISPB ou Code
          required: true
          schema:
            type: string
            description: O Id corresponde ao ISPB ou Code
            nullable: true
            example: '332'
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
              example:
                name: Acesso Soluções De Pagamento S.A.
                ispb: '13140088'
                code: '332'
                shortName: Acesso Solucoes Pagamento Sa
                isSPIDirect: true
                products:
                  - TED
                  - PIX
        '400':
          description: Há algum problema com a sua requisição.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Recurso não encontrado.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ocorreu algum erro inexperado no nosso servidor.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Bearer: []
  
  /states/{state}/cities:
    get:
      tags:
        - Endereços
      summary: Listagem de cidades por sigla do estado
      description: Obtenha a lista das cidades através da sigla do estado.
      operationId: GetCity
      parameters:
        - name: state
          in: path
          description: "Sigla do estado brasileiro conforme a ISO 3166-2:BR.\r\n'AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'"
          required: true
          schema:
            type: string
            description: "Sigla do estado brasileiro conforme a ISO 3166-2:BR.\r\n'AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'"
            nullable: true
            example: SP
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - Adamantina
                - Adolfo
                - Aguaí
                - Águas da Prata
                - Águas de Lindóia
                - Águas de Santa Bárbara
                - Águas de São Pedro
                - Agudos
                - Alambari
                - Alfredo Marcondes
                - Altair
                - Altinópolis
                - Alto Alegre
                - Alumínio
                - Álvares Florence
                - Álvares Machado
                - Álvaro de Carvalho
                - Alvinlândia
                - Americana
                - Américo Brasiliense
                - Américo de Campos
                - Amparo
        '400':
          description: Há algum problema com a sua requisição.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Recurso não encontrado.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ocorreu algum erro inexperado no nosso servidor.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Bearer: []
components:
  parameters:
    authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
  schemas:
    Address:
      type: object
      properties:
        zipCode:
          type: string
          description: O CEP correspondente ao endereço
          nullable: true
        addressLine:
          type: string
          description: Nome da rua (ou avenida)
          nullable: true
        neighborhood:
          type: string
          description: Nome do bairro ou distrito
          nullable: true
        city:
          type: string
          description: Nome da cidade
          nullable: true
        state:
          type: string
          description: "Sigla do estado brasileiro conforme a ISO 3166-2:BR.\r\n'AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'"
          nullable: true
        country:
          type: string
          description: 'Sigla do país (Brasil) conforme a ISO 3166-2. Exemplo: BR.'
          nullable: true
      additionalProperties: false
    
    Error:
      type: object
      properties:
        code:
          type: string
          nullable: true
        propertyName:
          type: string
          nullable: true
        messages:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          nullable: true
        reference:
          type: integer
          format: int32
      additionalProperties: false

    Product:
      enum:
        - TED
        - PIX
        - accountPortability
      type: string
      description: Nome do produto.


    Bank:
      type: object
      properties:
        name:
          type: string
          description: Nome do banco.
          nullable: true
        ispb:
          type: string
          description: ISPB (Identificador de Sistema de Pagamentos Brasileiro) do banco.
          nullable: true
        code:
          type: string
          description: Código do banco. Normalmente identificado nas transferências STR (TED). Este campo somente é retornado caso a instituição seja participante do PIX.
          nullable: true
        shortName:
          type: string
          description: Nome reduzido do banco.
          nullable: true
        isSPIDirect:
          type: boolean
          description: Indica se o banco é um participante direto do SPI (Pix).
          nullable: true
        products:
          type: array
          items:
            type: string
          description: Lista que contém os produtos suportados pelo registro da instituição financeira (TED, PIX e/ou accountPortability).
          nullable: true
        accountPortabilityTypes:
          type: array
          items:
            type: string
          description: Lista que contém as funções do banco, referente à portabilidade de salário ("Payroll" e/ou "Destination"). Este campo somente é retornado caso o banco possua portabilidade de salário (accountPortability) como produto.
      additionalProperties: false  
## TODO: colocar ponto final
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer.
      scheme: bearer
      bearerFormat: JWT
      
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
