openapi: 3.0.3
info:
  title: Gestão de Clientes
  description: |
    Registre, atualize, consulte o cadasto de clientes pessoa física ou
    jurídica. Um cliente com cadastro pode se tornar titular de contas de
    pagamento e cartões de crédito (pré-pago).
  version: '1.0'
servers:
  - url: 'https://api-mtls.sandbox.bankly.com.br'
paths:
  /customers/{documentNumber}:
    get:
      tags:
        - Pessoa física
      summary: |
        Consulta do registro do cliente
      description: |
        <div class="bkly-ref-description">
          <p>Obtenha um resultado resumido (BASIC) ou detalhado (DETAILED) dos dados de registro de um cliente.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: customer.read</span>
        </div>
      operationId: GetCustomerRegistration
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/CustomerDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ResultLevel'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
              examples:
                CustomerApproved:
                  value:
                    registerName: Peter Benjamin Parker
                    socialName: Peter Parker
                    birthDate: '1990-10-14'
                    phone:
                      countryCode: '55'
                      number: '11987654321'
                    address:
                      zipcode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      country: BR
                      state: SP
                      city: Sao Paulo
                      complement: Sala roxa
                    isPoliticallyExposedPerson: false
                    motherName: Mary Parker
                    email: peter.parker@avengers.com
                    status: APPROVED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Registro da cliente aprovado
                CustomerReproved:
                  value:
                    registerName: Peter Parker
                    socialName: Peter Parker
                    birthDate: '1990-10-14'
                    phone:
                      countryCode: '55'
                      number: '11987654321'
                    address:
                      zipcode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      country: BR
                      state: SP
                      city: Sao Paulo
                      complement: Sala roxa
                    isPoliticallyExposedPerson: false
                    motherName: Mary Parker
                    email: peter.parker@avengers.com
                    status: REPROVED
                    reasons:
                      - SELFIE_RECUSED
                      - NAME_RECUSED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Registro do cliente reprovado
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '404':
          $ref: 'http://localhost:3320/commons/components#/components/responses/404'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
    put:
      tags:
        - Pessoa física
      summary: Registro de pessoa física
      description: |
        <div class="bkly-ref-description">
          <p>O pedido de registro será analisado e você pode obter o resultado consultando o registro do cliente. Caso o cadastro não exista, ele será criado. Se já existir, os dados serão sobrepostos.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: customer.write</span>
        </div>      
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Os possíveis status do cliente após essa análise são: PENDING_APPROVAL, APPROVED, REPROVED, BLOCKLISTED. Para mais informações, consulte a documentação [Onboarding Completo](/docs/onboarding-completo)."
        }
        [/block]
      operationId: PutCustomerRegistration
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/CustomerDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCustomerRequest'
      responses:
        '202':
          $ref: 'http://localhost:3320/commons/components#/components/responses/202'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
  
  /customers/{documentNumber}/cancel:
    patch:
      tags:
        - Pessoa física
      summary: |
        Offboarding de pessoa física
      description: |
        <div class="bkly-ref-description">
          <p>Solicite o o cancelamento de relacionamento do cliente pessoa física.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: customer.cancel</span>
        </div>
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "É preciso realizar a exclusão de <b> todas as chaves Pix </b> atreladas ao documento antes de solicitar o seu Offboarding."
        }
        [/block]
      operationId: CancelCustomerRegistration
      parameters:
        - $ref: http://localhost:3320/commons/components#/components/parameters/CustomerDocument
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelRequest'
      responses:
        '202':
          $ref: 'http://localhost:3320/commons/components#/components/responses/202'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
  
  /business/{documentNumber}:
    get:
      tags:
        - Pessoa jurídica
      summary: |
        Consulta do registro da empresa
      description: |
        <div class="bkly-ref-description">
          <p>Obtenha um resultado resumido (BASIC) ou detalhado (DETAILED) dos dados de registro de uma empresa.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: business.read</span>
        </div>      
      operationId: GetBusinessRegistration
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/BusinessDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ResultLevel'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessResponse'
              examples:
                BusinessApproved:
                  value:
                    businessName: Peter Benjamin Parker
                    tradingName: Spider Man
                    businessEmail: spiderman@avengers.com
                    businessType: MEI
                    businessSize: MEI
                    businessAddress:
                      zipCode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      city: Sao Paulo
                      state: SP
                      country: BR
                      complement: Sala roxa
                    legalRepresentative:
                      registerName: Peter Benjamin Parker
                      socialName: Peter Parker
                      phone:
                        countryCode: '55'
                        number: '11987654321'
                      address:
                        zipCode: '05402100'
                        addressLine: Av. Rebouças
                        buildingNumber: '1368'
                        neighborhood: Pinheiros
                        city: Sao Paulo
                        state: SP
                        country: BR
                        complement: Sala roxa
                      birthDate: '1990-10-14'
                      motherName: Mary Parker
                      email: peter.parker@avengers.com
                    status: APPROVED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Registro da empresa aprovado
                BusinessRepproved:
                  value:
                    businessName: Peter Benjamin Parker
                    tradingName: Spider Man
                    businessEmail: spiderman@avengers.com
                    businessType: MEI
                    businessSize: MEI
                    businessAddress:
                      zipCode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      city: Sao Paulo
                      state: SP
                      country: BR
                      complement: Sala roxa
                    legalRepresentative:
                      registerName: Peter Benjamin Parker
                      socialName: Peter Parker
                      phone:
                        countryCode: '55'
                        number: '11987654321'
                      address:
                        zipCode: '05402100'
                        addressLine: Av. Rebouças
                        buildingNumber: '1368'
                        neighborhood: Pinheiros
                        city: Sao Paulo
                        state: SP
                        country: BR
                        complement: Sala roxa
                      birthDate: '1990-10-14'
                      motherName: Mary Parker
                      email: peter.parker@avengers.com
                    status: REPROVED
                    reasons:
                      - SELFIE_RECUSED
                      - STATUS_RECUSED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Registro da empresa reprovado
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '404':
          $ref: 'http://localhost:3320/commons/components#/components/responses/404'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
    put:
      tags:
        - Pessoa jurídica
      summary: Registro de pessoa jurídica (MEI, ME, EI ou EIRELI)
      description: |
        <div class="bkly-ref-description">
          <p>O pedido de registro será analisado e você pode obter o resultado consultando o registro da empresa. Caso o cadastro não exista, ele será criado. Se já existir, os dados serão sobrepostos.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: business.write</span>
        </div>        
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Os possíveis status da empresa após essa análise são: _APPROVED, REPROVED, REVOKED, BLOCKED_."
        }
        [/block]
      operationId: PutBusinessRegistration
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/BusinessDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBusinessRequest'
      responses:
        '202':
          $ref: 'http://localhost:3320/commons/components#/components/responses/202'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
  
  /business/{documentNumber}/cancel:
    patch:
      tags:
        - Pessoa jurídica
      summary: |
        Offboarding de pessoa jurídica
      description: |
        <div class="bkly-ref-description">
          <p>Solicite o o cancelamento de relacionamento do cliente pessoa jurídica.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: business.cancel</span>
        </div>
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "É preciso realizar a exclusão de <b> todas as chaves Pix </b> atreladas ao documento antes de solicitar o seu Offboarding."
        }
        [/block]
      operationId: CancelBusinessRegistration
      parameters:
        - $ref: http://localhost:3320/commons/components#/components/parameters/BusinessDocument
        - $ref: http://localhost:3320/commons/components#/components/parameters/ApiVersion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelRequest'
      responses:
        '202':
          $ref: 'http://localhost:3320/commons/components#/components/responses/202'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'

  /corporation-business/{documentNumber}:
    put:
      tags:
        - Pessoa jurídica
      summary: Registro de pessoa jurídica (LTDA, S.A. ou TS)
      description: | 
        <div class="bkly-ref-description">
          <p>
            Registre (ou substitua) uma nova empresa (LTDA, S.A. ou TS).
            O pedido de registro será analisado e você pode obter o resultado consultando o registro da empresa. Caso o cadastro não exista, ele será criado. Se já existir, os dados serão sobrepostos.
          </p>
          <span class="bkly-ref-small-beta-tag">beta</span> 
          <span class="bkly-ref-scope-tag">scope: business.write</span>
        </div>  
      
      operationId: RegisterCorporationBusinessAsync
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/BusinessDocument'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterCorporationBusinessRequest"
      responses:
        '201':
          description: Requisição foi aceita e está sendo processada.
          headers:
            x-bkly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
            Location:
              description: Localização do recurso recém-criado ou em análise.
              schema:
                type: string
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
      security:
      - Bearer: []
  
security:
  - Bearer: []

components:
  schemas:
    BusinessType:
      description: Tipo da empresa (MEI, EI, EIRELLI, LTDA, S.A. ou TS).
      type: string
      enum:
        - MEI
        - EI
        - EIRELI
        - LTDA
        - SA
        - TS
    BusinessSize:
      description: Porte da empresa (MEI, ME, EPP).
      type: string
      enum:
        - MEI
        - ME
        - EPP
    
    LegalRepresentative:
      required:
        - documentNumber
        - registerName
        - birthDate
        - phone
        - address
        - email
        - motherName
        - isPoliticallyExposedPerson
      type: object
      properties:
        incomeDeclared:
          type: number
          description: Renda declarada. Campo retornado somente para clientes do tipo LTDA / S.A. / TS.
          format: double
          nullable: true
        participationPercentage:
          type: string
          description: Percentual de participação (0 a 100). Campo retornado somente para clientes do tipo LTDA / S.A. / TS.
          nullable: true
        documentNumber:
          maxLength: 11
          minLength: 11
          type: string
          description: |
            Número do documento CPF. Informe somente números.
        registerName:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome conforme consta no documento de identificação (RG, CNH, RNE, DNI ou CRNM) do representante legal.
        socialName:
          type: string
          description: Nome pelo qual a pessoa gostaria de ser chamada. Para saber mais, consulte a [Cartilha do nome social](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf)
          nullable: true
        phone:
          description: Telefone de contato do representante legal da empresa.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Phone'
        address:
          description: Endereço do representante legal da empresa.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Address'
        birthDate:
          maxLength: 10
          minLength: 10
          type: string
          description: Data de nascimento do cliente. O representante legal deve possuir no mínimo **16 anos**.
          format: date-time
        motherName:
          type: string
          description: Nome da mãe do representante legal conforme consta no documento de identificação.
          nullable: true
        email:
          maxLength: 256
          minLength: 1
          type: string
          description: Endereço de e-mail. Um mesmo endereço de e-mail não poderá ser usado por dois clientes.
          format: email
        tradingName:
          type: string
          description: Nome fantasia da empresa (apenas para sócio pessoa jurídica). Campo retornado somente para clientes do tipo LTDA / S.A. / TS.
          nullable: true
        businessName:
          type: string
          description: Razão social da empresa (apenas para sócio pessoa jurídica). Campo retornado somente para clientes do tipo LTDA / S.A. / TS.
          nullable: true
        businessType:
          $ref: "#/components/schemas/BusinessType"
          description: Somente retornado para clientes do tipo LTDA / S.A. / TS.
        legalRepresentatives:
          type: array
          items:
            $ref: "#/components/schemas/LegalRepresentative"
          description: Representantes legais da empresa (apenas para sócio pessoa jurídica). Campo retornado somente para clientes do tipo LTDA / S.A. / TS.
          nullable: true
        isPoliticallyExposedPerson:
          description: Identificação do cliente como pessoa politicamente exposta.
          type: boolean
          default: false
        owners:
          type: array
          items:
            $ref: "#/components/schemas/LegalRepresentative"
          description: Sócios da empresa (apenas para sócio pessoa jurídica). Campo retornado somente para clientes do tipo LTDA / S.A. / TS.
          nullable: true
      additionalProperties: false
    
    Status:
      type: string
      description: Status do cliente.
      enum:
        - PENDING_APPROVAL
        - APPROVED
        - REPROVED
        - REVOKED
        - CANCELED
        - BLACKLISTED
    
    Profile:
      type: string
      description: Perfil do cliente.
      enum:
        - COMPLETE
        - SIMPLE
    
    RegisterCustomerRequest:
      required:
        - registerName
        - birthDate
        - phone
        - address
        - email
        - motherName
      type: object
      properties:
        registerName:
          maxLength: 256
          minLength: 1
          type: string
          description: >
            Nome conforme consta no documento de identificação (RG, CNH, RNE, DNI ou CRNM) do cliente.
        socialName:
          type: string
          description: >
            Nome pelo qual a pessoa gostaria de ser chamada. Saiba mais consultando a [Cartilha do nome social](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf)
          nullable: true
        phone:
          description: Telefone de contato do cliente.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Phone'
        address:
          description: Endereço do cliente.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Address'
        birthDate:
          maxLength: 10
          minLength: 10
          type: string
          description: |
            Data de nascimento do cliente. O cliente deve possuir no mínimo **16 anos**.
          format: date-time
        motherName:
          type: string
          description: >
            Nome da mãe do cliente conforme consta no documento de identificação.
          nullable: true
        email:
          maxLength: 256
          minLength: 1
          type: string
          description: >
            Endereço de e-mail. Um mesmo endereço de e-mail não poderá ser usado por dois clientes.
          format: email
        isPoliticallyExposedPerson:
          description: Identificação do cliente como pessoa politicamente exposta.
          type: boolean
          default: false
      additionalProperties: false
    
    RegisterBusinessRequest:
      required:
        - businessName
        - tradingName
        - businessAddress
        - businessEmail
        - businessSize
        - businessType
        - legalRepresentative
      type: object
      properties:
        businessName:
          maxLength: 256
          minLength: 1
          type: string
          description: Razão social da empresa. <b>Importante:</b> não é possível enviar caracteres especiais neste campo.
        tradingName:
          type: string
          description: Nome fantasia da empresa. <b>Importante:</b> não é possível enviar caracteres especiais neste campo.
          nullable: true
        businessEmail:
          type: string
          description: E-mail comercial da empresa.
          format: email
          nullable: false
        businessType:
          $ref: '#/components/schemas/BusinessType'
        businessSize:
          $ref: '#/components/schemas/BusinessSize'
        businessAddress:
          description: Endereço da empresa registrado no cartão CNPJ.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Address'
        legalRepresentative:
          description: Representante legal da empresa.
          $ref: '#/components/schemas/LegalRepresentative'
      additionalProperties: false
    CorporationBusinessType:
      enum:
        - LTDA
        - SA
        - TS
      type: string
    CorporationBusinessSize:
      enum:
        - SMALL
        - MEDIUM
        - LARGE
      type: string
    Owner:
      type: object
      properties:
        incomeDeclared:
          type: number
          description: Renda declarada.
          format: double
          nullable: true
        participationPercentage:
          type: string
          description: Percentual de participação (0 a 100).
          nullable: true
        documentNumber:
          type: string
          description: Número de documento (CPF ou CNPJ). Informe somente números.
          nullable: true
        registerName:
          type: string
          description: Nome conforme consta no documento de identificação (RG, CNH, RNE, DNI ou CRNM). Apenas para sócio pessoa física.
          nullable: true
        socialName:
          type: string
          description: Nome pelo qual a pessoa gostaria de ser chamada, saiba mais consultando a [Cartilha do nome social](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf). Apenas para sócio pessoa física. 
          nullable: true
        phone:
          $ref: "#/components/schemas/Phone"
        address:
          $ref: "#/components/schemas/Address"
        birthDate:
          type: string
          description: Data de nascimento do sócio. Apenas para sócio pessoa física.
          format: date-time
        motherName:
          type: string
          description: Nome da mãe do cliente conforme consta no documento de identificação. Apenas para sócio pessoa física.
          nullable: true
        email:
          type: string
          description: Endereço de e-mail do sócio.
          nullable: true
        tradingName:
          type: string
          description: Nome fantasia da empresa. Apenas para sócio pessoa jurídica.
          nullable: true
        businessName:
          type: string
          description: Razão social da empresa. Apenas para sócio pessoa jurídica.
          nullable: true
        businessType:
          $ref: "#/components/schemas/BusinessType"
        isPoliticallyExposedPerson:
          type: boolean
          description: Pessoa exposta politicamente. Apenas para sócio pessoa física.
        legalRepresentatives:
          type: array
          items:
            $ref: "#/components/schemas/LegalRepresentative"
          description: Representantes legais da empresa. Apenas para sócio pessoa
            jurídica.
          nullable: true
        owners:
          type: array
          items:
            $ref: "#/components/schemas/Owner"
          description: Sócios da empresa. Apenas para sócio pessoa jurídica.
          nullable: true
      additionalProperties: false
    Documentation:
      type: object
      required:
        - articlesOfIncorporation
        - lastContractChange
        - balanceSheet
        - legalRepresentative
      properties:
        articlesOfIncorporation:
          description: Id correspondente do documento do contrato social ou estatuto social da empresa.
          type: string
          nullable: true
        lastContractChange:
          description: Id correspondente do documento da última alteração contratual ou última ata de eleição.
          type: string
          nullable: true
        balanceSheet:
          description: Id correspondente do documento de declaração de faturamento dos últimos 12 meses ou balanço social.
          type: string
          nullable: true
        powerOfAttorney: 
          description:  Id correspondente do documento de procuração pública legal.
          type: string
          nullable: true
        legalRepresentative:
          $ref: "#/components/schemas/Image"
      additionalProperties: false
      
    Image:
      type: object
      description: Documentos de ao menos um dos representantes legais, é possível usar o RG, CNH, RNE, DNI e CRNM. 
      required:
        - documentNumber
        - selfie
        - idCardFront
        - idCardBack
      properties:
        documentNumber:
          description: Número do documento.
          type: string
          nullable: true
        selfie:
          description: Foto do representante legal.
          type: string
          nullable: true
        idCardFront:
          description: Imagem da frente do documento.
          type: string
          nullable: true
        idCardBack: 
          description: Imagem de trás do documento.
          type: string
          nullable: true
      additionalProperties: false
    RegisterCorporationBusinessRequest:
      required:
        - businessAddress
        - businessName
        - businessSize
        - businessType
        - cnaeCode
        - legalNature
        - openingDate
        - annualBilling
        - phone
        - legalRepresentative
      type: object
      properties:
        businessType:
          $ref: "#/components/schemas/CorporationBusinessType"
        businessSize:
          $ref: "#/components/schemas/CorporationBusinessSize"
        cnaeCode:
          type: string
          description: Código Cnae.
          nullable: true
        legalNature:
          type: string
          description: Natureza Jurídica da empresa.
          nullable: true
        openingDate:
          type: string
          description: Data de abertura da empresa.
          format: date-time
        annualBilling:
          type: number
          description: Faturamento anual da empresa.
          format: double
        phone:
          $ref: "#/components/schemas/Phone"
        legalRepresentatives:
          type: array
          items:
            $ref: "#/components/schemas/LegalRepresentativePerson"
          description: Representantes legais da empresa.
          nullable: true
        owners:
          type: array
          items:
            $ref: "#/components/schemas/Owner"
          description: Sócios da empresa. Campo obrigatório para empresas no formato LTDA;
          nullable: true
        businessName:
          maxLength: 256
          minLength: 1
          type: string
          description: Razão social da empresa.
        tradingName:
          type: string
          description: Nome fantasia da empresa.
          nullable: true
        businessEmail:
          type: string
          description: E-mail comercial da empresa.
          format: email
          nullable: true
        businessAddress:
          $ref: "#/components/schemas/Address"
        documentation:
          $ref: "#/components/schemas/Documentation"
      additionalProperties: false
    PowerOfAttorney:
      type: object
      properties:
        startDate:
          type: string
          description: Data de início da procuração.
          format: date-time
        endDate:
          type: string
          description: Data do fim da procuração.
          format: date-time
      additionalProperties: false        
    Address:
      required:
        - addressLine
        - buildingNumber
        - city
        - country
        - neighborhood
        - state
        - zipCode
      type: object
      properties:
        zipCode:
          minLength: 1
          type: string
          description: O CEP correspondente ao endereço.
        addressLine:
          maxLength: 256
          minLength: 1
          type: string
          description: Logradouro (Nome da rua, avenida etc.).
        buildingNumber:
          maxLength: 10
          minLength: 1
          type: string
          description: Número da residência.
        complement:
          maxLength: 256
          type: string
          description: 'Complemento do endereço. Exemplo: Apto 123, Casa B etc.'
          nullable: true
        neighborhood:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome do bairro ou distrito.
        city:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome da cidade.
        state:
          minLength: 1
          type: string
          description: Sigla do estado brasileiro conforme a ISO 3166-2:BR.
        country:
          minLength: 1
          type: string
          description: 'Sigla do país (Brasil) conforme a ISO 3166-2. Exemplo: BR.'
      additionalProperties: false
    LegalRepresentativePerson:
      type: object
      properties:
        powerOfAttorney:
          $ref: "#/components/schemas/PowerOfAttorney"
        memberQualification:
          type: string
          description: Qualificação de integrante.
          nullable: true
        socialName:
          type: string
          description: Nome pelo qual a pessoa gostaria de ser chamada. Saiba mais consultando a [Cartilha do nome social](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf)
          nullable: true
        birthDate:
          type: string
          description: Data de nascimento do representante legal. O cliente deve possuir no mínimo 16 anos.
          format: date-time
        motherName:
          type: string
          description: Nome da mãe do representante legal conforme consta no documento de identificação.
          nullable: true
        email:
          type: string
          description: Endereço de e-mail. Um mesmo endereço de e-mail não poderá ser usado por dois representante legal.
          nullable: true
        isPoliticallyExposedPerson:
          type: boolean
          description: Pessoa exposta politicamente.
        registerName:
          type: string
          description: Nome conforme consta no documento de identificação (RG, CNH, RNE, DNI ou CRNM) do representante legal.
          nullable: true
        phone:
          $ref: "#/components/schemas/Phone"
        address:
          $ref: "#/components/schemas/Address"
        documentNumber:
          type: string
          description: Número do documento CPF. Informe somente os números.
          nullable: true
          readOnly: true
      additionalProperties: false

    CustomerResponse:
      type: object
      properties:
        documentNumber:
          description: Número do documento CPF do cliente.
          type: string
        registerName:
          description: Nome conforme consta no documento de identificação (RG, CNH, RNE, DNI ou CRNM) do cliente.
          type: string
        socialName:
          description: >
            Nome pelo qual a pessoa gostaria de ser chamada. Saiba mais na documentação [Cartilha do nome social](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf).
          type: string
          nullable: true
        phone:
          description: Telefone de contato do cliente.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Phone'
        address:
          description: Endereço informado no registro do cliente.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Address'
        birthDate:
          description: Data de nascimento do cliente.
          type: string
          format: date-time
        email:
          description: E-mail de contato do cliente.
          type: string
          nullable: true
        motherName:
          description: Nome da mãe informado no registro do cliente.
          type: string
          nullable: true
        isPoliticallyExposedPerson:
          description: Identificação do cliente como pessoa politicamente exposta.
          type: boolean
        status:
          description: Status da análise KYC realizada no registro do cliente.
          $ref: '#/components/schemas/Status'
        profile:
          description: |
            Perfil do cliente, baseado no registro do cliente.
            _(SIMPLES, COMPLETO)_
          $ref: '#/components/schemas/Profile'
        createdAt:
          description: Data do primeiro registro do cliente.
          type: string
          format: date-time
        updatedAt:
          description: Data da atualização do registro do cliente.
          type: string
          format: date-time
          nullable: true
        reasons:
          description: Motivos de reprovação do registro do cliente.
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    
    BusinessResponse:
      type: object
      properties:
        documentNumber:
          description: Número do documento CNPJ da empresa.
          type: string
        businessName:
          description: Razão social da empresa.
          type: string
        tradingName:
          description: Nome fantasia da empresa.
          type: string
        email:
          description: E-mail comercial da empresa.
          type: string
        businessAddress:
          description: Endereço da empresa informado no registro.
          $ref: 'http://localhost:3320/commons/components#/components/schemas/Address'
        status:
          description: Status da análise KYC realizada no registro da empresa.
          $ref: '#/components/schemas/Status'
        businessType:
          description: |
            Tipo da empresa (MEI, EI, EIRELLI, LTDA, S.A.).
          $ref: '#/components/schemas/BusinessType'
        businessSize:
          description: |
            Porte da empresa (MEI, ME, EPP, SMALL, MEDIUM, LARGE).
          $ref: '#/components/schemas/BusinessSize'
        owners:
          description: Lista de sócios da empresa como consta no Quadro dos Sócios e Administradores (QSA).
          type: array
          items:
            $ref: '#/components/schemas/LegalRepresentative'
        legalRepresentatives:
          description: Lista de representantes legais da empresa.
          type: array
          items:
            $ref: '#/components/schemas/LegalRepresentative'
        createdAt:
          description: Data do primeiro registro da empresa.
          type: string
          format: date-time
        updatedAt:
          description: Data da atualização do registro da empresa.
          type: string
          format: date-time
          nullable: true
        cnaeCode:
          type: string
          nullable: true
          description: Somente retornado para clientes do tipo LTDA / S.A. / TS.
        legalNature:
          type: string
          nullable: true
          description: Somente retornado para clientes do tipo LTDA / S.A. / TS.
        annualBilling:
          type: number
          format: double
          description: Somente retornado para clientes do tipo LTDA / S.A. / TS.
        openingDate:
          type: string
          format: date-time
          description: Somente retornado para clientes do tipo LTDA / S.A. / TS.
        phone:
          $ref: "#/components/schemas/Phone"
          description: Somente retornado para clientes do tipo LTDA / S.A. / TS.
        reasons:
          description: Motivos de reprovação do registro da empresa.
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    
    ReasonType:
      type: string
      description: |
        Motivo do cancelamento. 
        _Default: **HOLDER_REQUEST**_.
      default: HOLDER_REQUEST
      enum:
        - HOLDER_REQUEST
        - COMMERCIAL_DISAGREEMENT
    Phone:
      required:
      - countryCode
      - number
      type: object
      properties:
        countryCode:
          minLength: 1
          type: string
          description: Código DDI do país. Por enquanto é permitido apenas 55 ou +55
            (Brasil).
        number:
          minLength: 1
          type: string
          description: Número de telefone incluindo DDD.
      additionalProperties: false
    CancelRequest:
      type: object
      properties:
        reason:
          $ref: '#/components/schemas/ReasonType'
      additionalProperties: false
  
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT

x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
